<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>2.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tools\**" />
    <None Remove="tools\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
    <PackageReference Include="System.IO.Ports" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

</Project>
